spring.application.name=devopsdemo

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/devopsdemo

spring.datasource.username=postgres

spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true